export const GAME_IS_NOT_STARTED = 'GAME_IS_NOT_STARTED'
export const GAME_START_IS_REQUESTED = 'GAME_START_IS_REQUESTED'
export const GAME_IS_STARTED = 'GAME_IS_STARTED'
export const GAME_IS_FINISHED = 'GAME_IS_FINISHED'
